### ISSUE TITLE
Cannot edit redirects

### ISSUE THREAD

**Issue by MattRogowski** [riasvdv/statamic-redirect#1]
When you try and edit a redirect, you get an error `A non well formed numeric value encountered`, because the `edit` method typehints `$id` to be an `int`, but the ID is actually a UUID.

Happens on 1.1.0

**Comment by riasvdv** [comment]
Could you post a full stacktrace? The typehints are only in the docblocks, so I'm thinking it's a different issue

**Comment by MattRogowski** [comment]
![image](https://user-images.githubusercontent.com/545339/94474055-faed3700-01c4-11eb-8260-4614a6e9cafc.png)

It's this line: https://github.com/riasvdv/statamic-redirect/blob/master/src/Controllers/RedirectController.php#L35

The typehint is in the method definition.

**Comment by riasvdv** [comment]
Ah, definitely incorrect. Fixed in 1.1.1!
