### ISSUE TITLE
Redirect not working

### ISSUE THREAD

**Issue by Hesesses** [riasvdv/statamic-redirect#10]
Hello,

I'm testing locally redirects, but for some reason is not working:

![image](https://user-images.githubusercontent.com/2721970/114692820-a608ac80-9d21-11eb-8481-af2f88a461f0.png)
when entering the default root (/) nothing happens.

I have a multisite setup and latest statamic version

Any ideas whats wrong?

Edit:
also deleting is not doing anything:
![image](https://user-images.githubusercontent.com/2721970/114693511-5676b080-9d22-11eb-87ac-b01a1f168f24.png)

Console error: ` Cannot read property '0' of undefined`

**Comment by riasvdv** [comment]
That's probably an edge case, didn't think someone would want to redirect the homepage.

I'll take a look at it ASAP

**Comment by riasvdv** [comment]
Redirecting the homepage should work, but redirects only trigger on a 404, you have to make sure that the homepage "/" is not found, otherwise this addon doesn't redirect, as checking all redirects for all requests would slow everything down.
