### ISSUE TITLE
Support Eloquent redirects

### ISSUE THREAD

**Issue by FrittenKeeZ** [riasvdv/statamic-redirect#106]
As the title says, there's no way to store redirects in the database, which prevents easy load balancing and backup when using the Eloquent driver - also the database table should have a configurable prefix to prevent clashes with other tables.

**Comment by FrittenKeeZ** [comment]
@riasvdv any thoughts regarding this?

**Comment by riasvdv** [comment]
It's currently a lot of work to implement this, if I get more requests I'll look more into it (others can upvote this issue)

**Comment by klickreflex** [comment]
﻿I'm not sure if I understand the docs correctly and this has been implemented. If I add the eloquent repositories, I still get YAML files generated containing the redirects, is this how it should be?

<img width="653" alt="CleanShot 2023-11-26 at 11 57 47@2x" src="https://github.com/riasvdv/statamic-redirect/assets/435825/d6313b4a-2737-417f-9339-7d87af50f336">
