### ISSUE TITLE
Conflict with versions of spatie/simple-excel

### ISSUE THREAD

**Issue by mscruse** [riasvdv/statamic-redirect#108]
I've encountered an issue where this package is using an old version (1.9) of Spatie's Simple Excel package.

Another part of my site and app is using the latest 3.x version.

Because of this, I am unable to install the Stataimc Redirect add-on.

Is it possible to have this add-on updated to support Spatie's 3.x version? I've had this issue on 2 of your add-ons - this one I more important for me to get sorted and installed.

**Comment by riasvdv** [comment]
Should be fixed in 2.6.0, I'll check the other addons soon
