### ISSUE TITLE
Handling of 410 Gone

### ISSUE THREAD

**Issue by nelo-digitalagentur** [riasvdv/statamic-redirect#11]
Hi,

the blueprints (https://github.com/riasvdv/statamic-redirect/blob/master/src/Blueprints/RedirectBlueprint.php) for redirects supports the 410 gone response code. 

Sad but true, there is no handling in your middleware for this response code which leads to

```[2021-05-03 12:55:00] local.DEBUG: InvalidArgumentException: The HTTP status code is not a redirect ("410" given)```

**Comment by riasvdv** [comment]
Should be fixed in 1.4.4, the 410 Gone status doesn't return any content though as it's not a redirect status code.

**Comment by nelo-digitalagentur** [comment]
Hi @riasvdv 

thanks for your fast response! Sad but true the handling is only slightly better now, because:

1. The 410 handling works the first time but is cached and fails with the mentioned error each time after this
2. There should be a response with the 410.antlers.html template used

Any chance you might re-open this issue?

Thanks,

Andreas

**Comment by riasvdv** [comment]
If you change the code here https://github.com/riasvdv/statamic-redirect/blob/master/src/Http/Middleware/HandleNotFound.php#L62 in the middleware to an `abort(410)` does that solve your issue?

**Comment by mmolle-nelo** [comment]
Hi @riasvdv,

using the `abort(410)` method does not help either as this throws a `HttpException` which is instantly catched by the middleware, which results in an `404` error page.

Thanks,
Martin

**Comment by riasvdv** [comment]
I'll take another look at it tonight, that exception should bubble up and then it'll be fixed

**Comment by riasvdv** [comment]
This should really be fixed now in 1.4.5!

**Comment by mmolle-nelo** [comment]
Hi @riasvdv,

thank you for the fast response.

In version 1.4.5, the first request to a 410 redirect is handled correctly now, but as the redirect gets cached on https://github.com/riasvdv/statamic-redirect/blob/master/src/Http/Middleware/HandleNotFound.php#L56, all further requests to the the same URI runs into the original error (`InvalidArgumentException: The HTTP status code is not a redirect ("410" given)`).

Can you please have another look on this?

Regards,
Martin

**Comment by riasvdv** [comment]
Sorry about that, didn't test the cached version, this should be fixed in 1.4.6
