### ISSUE TITLE
Auto commit

### ISSUE THREAD

**Issue by joedelia** [riasvdv/statamic-redirect#111]
Hello!

Trying to figure out why changing redirects does not trigger an automatic git commit. Is [this bit](https://statamic.dev/git-automation#configuration:~:text=When%20building%20an%20addon%20that%20provides%20its%20own%20content%20saved%20events) missing from the addon?

Joe

**Comment by riasvdv** [comment]
That does look like it's missing, I'll look into it soon!

**Comment by joedelia** [comment]
Thank you @riasvdv!

**Comment by riasvdv** [comment]
2.7.0 should have this feature!
