### ISSUE TITLE
Statamic v4 Support Hides Live Preview

### ISSUE THREAD

**Issue by CCCowley** [riasvdv/statamic-redirect#116]
As originally highlighted here: https://github.com/statamic/cms/issues/8128#issuecomment-1547904706

The v4 support update added this style, hiding the Statamic's live preview from appearing:
`.publish-tab-actions {
     display: none;
   }`

https://github.com/riasvdv/statamic-redirect/commit/e2c9787d5be6ed871a150ee3be281e78a1d4ad11#diff-1177986ccc12eb2db151ee46c6bf95739d7961b9427139dfb245702ca32e77c1R12-R17

**Comment by riasvdv** [comment]
Sorry about that! 3.0.1 should solve this issue
