### ISSUE TITLE
EntrySaved listener to delete redirect conflicts is case-insensitive, Laravel/Statamic routing is case-sensitive

### ISSUE THREAD

**Issue by galengidman** [riasvdv/statamic-redirect#117]
I have an issue where a client has a page at `/eula`, but links in the wild to `/EULA`. Laravel/Statamic's routing is case sensitive so visiting `/EULA` results in a 404. He created a redirect for `/EULA` -> `/eula`, but now when he saves his `/eula` entry, [this code](https://github.com/riasvdv/statamic-redirect/blob/main/src/Listeners/CreateRedirect.php#L25-L27) automatically deletes the redirect because the `findByUrl` method [has a case-insensitive check](https://github.com/riasvdv/statamic-redirect/blob/main/src/Data/Redirect.php#L88-L89).

**Comment by riasvdv** [comment]
I've renamed the config key to `delete_conflicting_redirects`
