### ISSUE TITLE
url with params

### ISSUE THREAD

**Issue by Hesesses** [riasvdv/statamic-redirect#12]
Hello,

I have created a redirect with `/old-product-name` -> `/new-product-name` which is working fine.

We are using google ads to drive traffic and noticed that on ´/old-product-name?gclid=CjwKC...` shows red (not handled) on redirect dashboard.

When manually trying the url, its redirected to the `/new-product-name` 

Is this a bug on dashboard or is the redirection broken some how?

**Comment by riasvdv** [comment]
If you're using an exact match redirect it will not match the query parameters, it's better to create a regex match redirect then with this as source:

```
/old-product-name(.*)
```
