### ISSUE TITLE
Ability to search redirects

### ISSUE THREAD

**Issue by cristawebadmin** [riasvdv/statamic-redirect#124]
We currently have a lot of redirects on our site since we migrated from a different CMS to Statamic. That said, it would be great to have a search bar in the Redirects page to easily manage existing redirects.

**Comment by dadaxr** [comment]
Actually there is a search bar on the "redirects" page : 

![image](https://github.com/riasvdv/statamic-redirect/assets/1267495/0141d864-33b1-483b-ba69-cf2bf06a9bcb)

there is also one the "dashboard" page but it does not seems to work ... (ie : neither the filter, or "handled" or inputing some text in the search bar, work ... no error in the console, it just do nothing) 

![image](https://github.com/riasvdv/statamic-redirect/assets/1267495/163fb7ef-49ac-44db-9827-30ee48233b6a)

@riasvdv  Should I open a new issue ?

**Comment by maartenvanhunsel** [comment]
@riasvdv +1
Our client does have more then 8000 redirects which is hardly to organize without search capabilities?

**Comment by riasvdv** [comment]
Small preview that I am working on this:

![image](https://github.com/riasvdv/statamic-redirect/assets/3626559/fd72b98b-63c9-42ba-85cd-9d17a04c7a08)

Have not gotten all use cases working yet but will release an update soon!

**Comment by riasvdv** [comment]
You can now search redirects both on source & destination in 3.2.0!
