### ISSUE TITLE
Huge stache performance problems on big site with lots of traffic and errors

### ISSUE THREAD

**Issue by AndreasSchantl** [riasvdv/statamic-redirect#14]
I do experience huge performance problems on a recently moved site. It seems that at some point, it's just too much for the stache to handle. Is there any plan to add database support by default?

I'd be willing to write a PR for a repository using a database if wanted.

**Comment by mattrothenberg** [comment]
@riasvdv I think I'm also getting bitten by this. Happy to share relevant logs or metrics!

**Comment by riasvdv** [comment]
This addon contains a scheduled command that cleans errors according to the settings in the addon config https://github.com/riasvdv/statamic-redirect/blob/master/src/Commands/CleanErrorsCommand.php

You should be able to run this manually as well, but you can look into running the schedule automatically https://laravel.com/docs/8.x/scheduling#running-the-scheduler

**Comment by mattrothenberg** [comment]
Running that task hangs on my server. I also noted that I couldn't even manually `rm *.yaml` from `storage/logs/errors` because there were too many arguments to that command.

Currently, I can't access the "Dashboard" CP view without the page timing out.

**Comment by mattrothenberg** [comment]
Curious! 

My situation was definitely being exacerbated by my site going through a DDoS attack. Anecdotally, though, after disabling error logging via setting `log_errors` to false, my site's CPU/Memory usage dropped precipitously and things seem to be doing better again!

**Comment by riasvdv** [comment]
I've added an extra config key `log_hits` that you can disable to remove the logging of individual hits against a 404. This way you can keep the main 404 errors, but performance won't be impacted as much by a lot of hits.

I'll try to work on an Eloquent repository soon

**Comment by riasvdv** [comment]
So I've added 2 eloquent repositories, which should give you better performance with a large amount of Errors being logged.

https://github.com/riasvdv/statamic-redirect#using-the-eloquent-repositories

I've tried to test them as best as I could, let me know if you run into any issues by creating a new issue on this repository
