### ISSUE TITLE
Cleaning up Errors

### ISSUE THREAD

**Issue by lokmanm** [riasvdv/statamic-redirect#142]
Hey!

We disabled logging of `errors` and `hits` in one of our sites as it got huge and they didn't seem to clean up.

I tried running: `php artisan redirect:clean-errors` but I got this:

```
production.ERROR: Database connection [redirect] not configured. {"exception":"[object] (InvalidArgumentException(code: 0): Database connection [redirect] not configured. at /home/forge/site-here/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php:173)
```

I see an `SQLite` db in the `storage` folder. 

Is there any way we can clean up these errors by hand?

Thanks!

**Comment by riasvdv** [comment]
You can delete the file and it should be recreated automatically!

**Comment by riasvdv** [comment]
You can also enable logging again with the `statamic.redirect.log_errors` config setting and run the clean command and afterwards disable logging again.
