### ISSUE TITLE
Redirects only working with a trailing '/'

### ISSUE THREAD

**Issue by tmharryfrancis** [riasvdv/statamic-redirect#15]
Having an issue where redirects don't seem to be working as expected.

I have a redirect setup as: /articles/A > /articles/B

When I then visit /articles/A I don't get redirected, but if I append an extra '/' I do get redirected (//articles/A takes me to /articles/B).

I have setup the redirects as it suggests so wondering if this is a bug with the addon?

<img width="848" alt="Screenshot 2021-05-28 at 15 38 47" src="https://user-images.githubusercontent.com/73337049/120000568-dbfcaa00-bfca-11eb-9901-c4ed38e11fca.png">

Thanks! Harry.

**Comment by riasvdv** [comment]
Do you have any url rewriting enabled on your server in nginx or htaccess that messes with slashes?
