### ISSUE TITLE
Destination column empty

### ISSUE THREAD

**Issue by danielduner** [riasvdv/statamic-redirect#16]
The Destination column in the Redirect Dashboard doesn't show any results.

The feature was added after issue #3, but it doesn't seem to work for me. Is this a general issue with the plugin in its current state, or is something amiss with my installation?

Statamic 3.1.23
Statamic Redirect 1.4.6

**Comment by riasvdv** [comment]
The destination will only be filled when an error has had a successful redirect and marked as "handled"

**Comment by danielduner** [comment]
Yes, of course. The issue is with redirected destinations. I accidentally uploaded the wrong image in the initial comment. Here is an example:

![image](https://user-images.githubusercontent.com/148074/122411353-f9e37c00-cf84-11eb-9f16-6b747bd41ab2.png)

**Comment by riasvdv** [comment]
Fixed in 1.5.0!
