### ISSUE TITLE
Changes in conifg file breaks addon

### ISSUE THREAD

**Issue by christophstockinger** [riasvdv/statamic-redirect#167]
Hi @riasvdv 

We had to realize that the update to 3.6.0 causes the addon to stop working. After some research, we found out that the configuration file has been adapted and a previously undefined variable has now been converted to an ENV variable and its default value has also been changed. 

https://github.com/riasvdv/statamic-redirect/compare/3.5.0...3.6.0

Furthermore, this change is not documented anywhere.

Finally, for me this is also a breaking change and would therefore result in a major update!

**Comment by christophstockinger** [comment]
Our error: 
Database connection [redirect] not configured. {"exception":"[object] (InvalidArgumentException(code: 0): Database connection [redirect] not configured. at /home/forge/www-cdn.involve.me/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php:173)
[stacktrace]

**Comment by atomicjam** [comment]
We are having the same issue #168 details logged in separate issue.

**Comment by riasvdv** [comment]
Sorry about that, this should be fixed in the latest release!
