### ISSUE TITLE
Allow same URL for different sites (multi-site)

### ISSUE THREAD

**Issue by rubzie** [riasvdv/statamic-redirect#171]
Multi site support is great, but currently you cannot make the same redirect source URL on multiple sites. It will give an error "This source already has a redirect associated with it.

It would be good to check for uniqueness per site, not across the complete install (or more precisely, to include the base url of the site, in case you have a site with a base url that's part of another site, cuz then you could make duplicate redirects)

**Comment by finnjsmith** [comment]
This is a real sticking point for me, and is the reason I'm not able to use this add-on in my project.

**Comment by mickeyhub** [comment]
😀
