### ISSUE TITLE
Does `schedule:run` automatically run `redirect:clean-errors`?

### ISSUE THREAD

**Issue by aaronbushnell** [riasvdv/statamic-redirect#175]
Sorry for the basic question here!

If I'm running `php artisan schedule:run` will that automatically invoke `redirect:clean-errors` based on the config settings? I ask because I currently have a schedule job that runs every minute but I got the...

> Error cleanup has not ran for 2 days

...message in the dashboard until I manually called that command.

**Comment by riasvdv** [comment]
We have defined it like the Statamic docs describe: https://statamic.dev/extending/addons#scheduling

When you run `php artisan schedule:list` does it list it in there?
