### ISSUE TITLE
Redirects created when non-published entries have slug change

### ISSUE THREAD

**Issue by cstilstra** [riasvdv/statamic-redirect#177]
I think that perhaps it is better if redirects are only created in response to published entries being saved. Because the check to remove conflicting redirects only happens if the entry is published, this can lead to a situation where circular redirects are possible (though they would have no effect since no 404 would be generated). It seems to me that it would be better coding practice and less surprising behavior for developers if the logic to create a redirect on entry change and the logic to remove conflicting redirects were the same (ie: both either do or don't care about whether the entry is published).

To repro:

1. create an entry that is not published
2. edit the entry and change the slug
3. notice that a redirect from old_slug to new_slug will have been created
4. edit the entry again and change the slug back to the old slug
5. notice that a redirect from new_slug to old_slug now exists alongside the redirect from old_slug to new_slug

**Comment by riasvdv** [comment]
Should be fixed in 3.7.1!
