### ISSUE TITLE
Showing an update is available when I have the latest version of Redirect

### ISSUE THREAD

**Issue by aaronbushnell** [riasvdv/statamic-redirect#183]
Looks like this issue statamic/cms#10277 from the Statamic repo is causing Redirect to errantly say it's not up-to-date when you have the latest version. Here's what @duncanmcclean [recommended](https://github.com/statamic/cms/issues/10277#issuecomment-2277693729) to correct this:

>- If the addon's latest release was tagged before we deployed our fix yesterday, the addon developer will need to re-save their addon on the Marketplace in order to force Statamic.com to sync with GitHub.
>- If the addon's latest release was tagged after we deployed our fix yesterday, it probably means the issue is back 😞. In which case, please leave a comment on this issue and we can take a look.

Is this something that could be corrected? 🙏

**Comment by duncanmcclean** [comment]
Should be fixed on the Statamic side now.

**Comment by aaronbushnell** [comment]
Thanks, @duncanmcclean! Worked after I wiped the cache and did a fresh `composer install` for good measure
