### ISSUE TITLE
Broken layout if URLs is not wrapping

### ISSUE THREAD

**Issue by rrelmy** [riasvdv/statamic-redirect#22]
If there is a long path the layout is broken. Example: `/this/is/long/this/is/long…`

Adding `word-break: break-all;` to the title would help

<img width="1208" alt="Redirects_‹_Statamic" src="https://user-images.githubusercontent.com/442683/131839910-00774954-3f1d-42db-ad5f-00628891fd0d.png">

**Comment by riasvdv** [comment]
Good catch! I'll fix this soon

**Comment by riasvdv** [comment]
Fixed in 1.5.0!

**Comment by josephrlee** [comment]
I'm having the issue happen again in the Redirects window now:
<img width="2380" alt="Screen Shot 2022-01-11 at 5 20 16 PM" src="https://user-images.githubusercontent.com/1631062/149046952-c592c31f-e077-41c4-b5e9-268ae11a8e60.png">

**Comment by riasvdv** [comment]
Ah, should have thought to add it there as well, should be fixed in 1.10.1!
