### ISSUE TITLE
Delete button doesn't work

### ISSUE THREAD

**Issue by elmanvebs** [riasvdv/statamic-redirect#24]
Hi,

It worked, but then it stopped. Can't delete anything, when I press on `Delete` button, nothing happens.

**Comment by riasvdv** [comment]
Have you tried republishing the assets? 

Things have changed in a recent update

You can do this using

`php artisan vendor:publish --provider="Rias\StatamicRedirect\RedirectServiceProvider" --force`

**Comment by elmanvebs** [comment]
@riasvdv 

Thanks, it did the trick.
