### ISSUE TITLE
route:cache fails because of duplicated route "redirect.redirects.import"

### ISSUE THREAD

**Issue by onelovefame** [riasvdv/statamic-redirect#25]
In version 1.6.0 the import functionality was introduced - with 2 new routes. 

These routes were created under the same name "redirect.redirects.import" - one for GET, one for POST. 
(File: [routes/cp.php](https://github.com/riasvdv/statamic-redirect/blob/main/routes/cp.php))

As a result, we now get a serialisation error with the route:cache command. 

```
LogicException  
Unable to prepare route [redaktion/redirect/redirects/import] for serialization. Another route has already been assigned name [statamic.cp.redirect.redirects.import].

  at vendor/laravel/framework/src/Illuminate/Routing/AbstractRouteCollection.php:218
```

**Comment by riasvdv** [comment]
Should be fixed in 1.6.1!
