### ISSUE TITLE
Exclude non production environments?

### ISSUE THREAD

**Issue by sunscreem** [riasvdv/statamic-redirect#30]
Wondering if it's possible to exclude non-production environments from triggering potential redirects?

**Comment by riasvdv** [comment]
This is currently not possible, I'll see if I can add a config value for that

**Comment by riasvdv** [comment]
I've added a config value `statamic.redirect.enable` that you can set to false or to something like this:

```php
'enable' => env('APP_ENV') === 'production',
```

To enable the functionality only when you want.

**Comment by sunscreem** [comment]
@riasvdv Awesome!
