### ISSUE TITLE
Slow performance in production

### ISSUE THREAD

**Issue by josephrlee** [riasvdv/statamic-redirect#33]
I have the Redirect Add-On installed on my site, and I'm noticing it's pretty slow at displaying the dashboard and more often then not just doesn't show anything at all. It's showing some 950+ pages worth of errors, the site was previously on Wordpress... Here's a screenshot of the dashboard, are there any tips on getting the add-on to be more performant? I'm using Digital Ocean and Ploi for my hosting/server management setup. Thanks!

![Redirect Dahsboard](https://user-images.githubusercontent.com/1631062/144281083-953a6839-a4ca-4d53-a0ac-4e59e8b60975.png)

**Comment by riasvdv** [comment]
If you have that many errors, error cleaning is not working, take a look at the docs to set it up correctly, make sure your Laravel schedule is also running 

https://statamic.com/addons/rias/redirect/docs
