### ISSUE TITLE
Question: How would you configure Redirect on load balanced servers?

### ISSUE THREAD

**Issue by mikemartin** [riasvdv/statamic-redirect#4]
Hey @riasvdv 
I've been using your Redirect addon for a client site. We have our development site (dev.example.com) and for production we deploy to four load balanced servers. What would you recommend for cleaning errors in this situation? or would you recommend disabling error tracking on our production sites altogether?

Thanks.

**Comment by riasvdv** [comment]
Don't really have any experience with load balanced servers, I assume you have a shared filesystem between them? Errors & redirects should be stored there, which would allow all servers to read & write those.

As for cleaning, I'd only schedule the cleaning on 1 server, or schedule it using Laravel's `onOneServer()` schedule function (https://laravel.com/docs/master/scheduling#running-tasks-on-one-server)
