### ISSUE TITLE
Feature Request - Multisite support

### ISSUE THREAD

**Issue by bobmulder** [riasvdv/statamic-redirect#49]
Hi Rias,

thank you for this awesome plugin! Just purchased the license and it works like a charm! I am using the plugin for a multisite, running on 5 different domains (and so 5 different languages).

I find it difficult that I only can manage all redirects for all sites in one dashboard, instead of managing them per multisite. I cannot see on what domain an unhandled redirect has been fired. Also, when I set a new redirect rule, it is applied on all multisites, while I want to manage it for one of them.

I do not know much about Statamics codebase, but is it hard to make this plugin support multisites?

Regards,

Bob

**Comment by riasvdv** [comment]
This will be a hard one to add, as the middleware for the redirects runs before any multisite / localisation from Statamic.

As for the redirect rules applying to all of them, don't your sites each have their own urls? I don't think there should be any collisions, could you give me an example?

I could add the site to a redirect rule as a field, but it would most likely just be something you can filter on instead of actually being separate for each site.

**Comment by FrittenKeeZ** [comment]
@riasvdv if you store a site handle, optionally `null`, for all redirects, you can use `Statamic\Facades\Site::findByUrl($request->url())` to find the current site, and filter all cached URLs having the same handle or `null`, and continue with the normal check after that.

**Comment by axelferdinand** [comment]
I would LOVE if this addon got multisite support...

**Comment by riasvdv** [comment]
Added in 2.3.0, let me know if everything works as expected!

**Comment by axelferdinand** [comment]
@riasvdv Wonderful!! Thank you so much!! 

However, when changing site – both in the global CMS header and in the redirects list – all created redirects are stored on the default site/locale – not the site you are currently on. And I can't find a way to "move" the redirects to the correct site.

**Comment by axelferdinand** [comment]
Have a look at the behavior here:
https://user-images.githubusercontent.com/10460870/169793333-63d1b1a0-6a40-4750-979b-721a2f4a7af0.mov

**Comment by axelferdinand** [comment]
I discovered another bug: When saving any entry, anywhere on the page, this happens:

<img width="1948" alt="image" src="https://user-images.githubusercontent.com/10460870/169799949-aa06ce69-95fa-464c-900a-08140ca9f8c2.png">

**Comment by axelferdinand** [comment]
Do you know how I can downgrade manually?

**Comment by riasvdv** [comment]
The exception should be fixed in 2.3.1, redirects saving in the wrong site will be fixed later tonight

**Comment by axelferdinand** [comment]
Perfect, thanks!

**Comment by riasvdv** [comment]
2.3.2 should fix the Redirect being saved in the wrong site, switching the site of a redirect can be done by switching at the top when editing the Redirect and then saving

**Comment by axelferdinand** [comment]
Fantastic! Thank you for fixing this so fast!
