### ISSUE TITLE
500 error on /cp/redirect/dashboard

### ISSUE THREAD

**Issue by AlexanderLindkjaer** [riasvdv/statamic-redirect#5]
Hi @riasvdv 

Going to the redirect dashboard throws this [error](https://flareapp.io/share/x7XgORVP)

vendor/rias/statamic-redirect/src/RedirectServiceProvider.php:54 
Class name must be a valid object or a string

Statamic `3.0.26` install.

**Comment by riasvdv** [comment]
Did you publish the config file? If so, could you show the contents?

**Comment by AlexanderLindkjaer** [comment]
@riasvdv i did not publish it. Tried to with the standard one and it still throws the error. I cant even run an ` php please stache:refresh` in the cli without it throwing the same error, so I have to leave the addon uninstalled.

**Comment by AlexanderLindkjaer** [comment]
I tried on a fresh install of the same site and it worked. So its something with my stache. However after I install the addon it breaks all stache operations so I'm a bit stumped on how to fix the stache. Will try to dig some more into it :)

**Comment by AlexanderLindkjaer** [comment]
It was the ```$class = config('statamic.redirect.error_repository');``` that returned null
doing `php artisan optimize` fixed it, sorry for the confusion :)
