### ISSUE TITLE
Missing migration drop statements

### ISSUE THREAD

**Issue by FrittenKeeZ** [riasvdv/statamic-redirect#50]
Either prefixing the tables with `redirect_` or allow a custom prefix would prevent clashes with other tables.
```php
public function down()
{
    Schema::dropIfExists('hits');
    Schema::dropIfExists('errors');
}
```

**Comment by riasvdv** [comment]
> Either prefixing the tables with redirect_ or allow a custom prefix would prevent clashes with other tables.
Redirect uses its own sqlite store, there shouldn't be any conflicts. As a result you shouldn't need down migrations either.

What issue are you running into exactly?

**Comment by FrittenKeeZ** [comment]
The use case is as simple as doing a `migrate:rollback` with other migrations included - this will blow up trying to run the migration again, since the tables already exists.
I couldn't get the eloquent driver to work though - the sqlite store seems to be forced.

**Comment by FrittenKeeZ** [comment]
Scratch that, I'd missed the `connection` configuration.
