### ISSUE TITLE
Incorrect value when inserting in error table with mysql driver

### ISSUE THREAD

**Issue by tomhelmer** [riasvdv/statamic-redirect#52]
When use MySQL as the database driver we get the following error :

[2022-03-17 14:27:18] local.DEBUG: PDOException: SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '1647523638' for column `ks`.`errors`.`lastSeenAt` at row 1 in /code/cms/vendor/laravel/framework/src/Illuminate/Database/Connection.php:501

**Comment by linuxtheblack** [comment]
Looks like the migration sets `lastSeenAt` as DateTime:
https://github.com/riasvdv/statamic-redirect/blob/21c5e47823a461a7ef3c6462e553fe288a775e5d/database/migrations/create_redirect_tables.php.stub#L17
But when trying to update the field, it's called with an int:
https://github.com/riasvdv/statamic-redirect/blob/21c5e47823a461a7ef3c6462e553fe288a775e5d/src/Data/Error.php#L37-L42

Could be solved by changing the `$timestamp` to datetime before updating.

**Comment by FrittenKeeZ** [comment]
Using an `integer` field to store a timestamp is far from best practice, when there's support for `TIMESTAMP` field, like Laravel does it for `created_at`/`updated_at` etc. It's something Drupal does...
