### ISSUE TITLE
Could not find driver (sqlite_master)

### ISSUE THREAD

**Issue by stuartcusackie** [riasvdv/statamic-redirect#54]
Hi, first time testing this add-on. After running composer require rias/statamic-redirect I get this error:
`Could not find driver (SQL: select * from sqlite_master where type = 'table' and name = errors)`

I've never used sqllite so I'm not sure what to do here. My app is using a mysql database at the primary driver so I'd rather not change that configuration.

Any ideas?

**Comment by riasvdv** [comment]
This addon stores the errors in a simple sqlite database file because it's a lot faster than using files on the filesystem. You'll need to have sqlite installed to use it though

Which operating system are you using?

**Comment by stuartcusackie** [comment]
I am on Windows. I have run the command shown in the Laravel documentation:
`touch database/database.sqlite`

As mentioned, I can't easily change my database connection in ENV file. It is being used for mysql for other application functionality.

**Comment by riasvdv** [comment]
Redirect uses its own file, you shouldn't need to change anything on your database connections. Windows probably doesn't come with sqlite by default.

You can try editing your `php.ini` file and uncommenting `php_pdo_sqlite.dll` if it was commented. If you're using something like xampp you can try searching Google on how to enable sqlite there.

**Comment by stuartcusackie** [comment]
Gotcha. Yep, rookie mistake, I did not enable sqllite on my local server (laragon).

I'll try the package out at a later date. Thanks!
