### ISSUE TITLE
Doesn't support PHP 7.4?

### ISSUE THREAD

**Issue by elmanvebs** [riasvdv/statamic-redirect#55]
Hi there,

It seems that the add-on doesn't support PHP 7.4?

Problem 1
    - Root composer.json requires rias/statamic-redirect 2.1.* -> satisfiable by rias/statamic-redirect[2.1.0, 2.1.1, 2.1.2].
    - rias/statamic-redirect[2.1.0, ..., 2.1.2] require php ^8.0 -> your php version (7.4.28) does not satisfy that requirement.

**Comment by riasvdv** [comment]
Statamic requires PHP 8 from 3.3, so this addon has changed to that requirement as well.

**Comment by elmanvebs** [comment]
> Statamic requires PHP 8 from 3.3, so this addon has changed to that requirement as well.

According to [Statamic's upgrade page](https://statamic.dev/upgrade-guide/3-2-to-3-3), it requires PHP 7.4.

**Comment by riasvdv** [comment]
Then that isn't updated, according to this https://github.com/statamic/statamic/blob/master/composer.json#L12 it's PHP 8

**Comment by elmanvebs** [comment]
Got it, thanks.
