### ISSUE TITLE
Redirect not created when changing entry parent

### ISSUE THREAD

**Issue by stuartcusackie** [riasvdv/statamic-redirect#56]
It seems that no redirect is being created automatically when I change the parent of an entry. This action changes the url of the entry so I think a redirect should be created?

Thanks.

**Comment by riasvdv** [comment]
Good catch! I'll see if I can fix this soon

**Comment by stuartcusackie** [comment]
Thank you!

I guess it should ideally work when dragging entries around in the collection tree too.
