### ISSUE TITLE
Having a .gitkeep file in content directory will crash the redirect store and the site

### ISSUE THREAD

**Issue by FrittenKeeZ** [riasvdv/statamic-redirect#58]
The `.gitkeep` file will be sourced as YAML and will have no content, causing a fatal error because `source` is missing.
Also imported redirects are not validated properly so they can contain empty destinations etc.

Edit: Something weird is happening because I can't reproduce the error locally, only on our production server.

**Comment by riasvdv** [comment]
> The .gitkeep file will be sourced as YAML and will have no content, causing a fatal error because source is missing.

Statamic should be filtering by default on only .yaml files, I can't seem to reproduce this either. Could you share the full stacktrace?

> Also imported redirects are not validated properly so they can contain empty destinations etc.

I've added basic validation on the rows for this, they'll be skipped if not all fields are entered

**Comment by riasvdv** [comment]
Closing for now, you can reopen an issue with the stacktrace
