### ISSUE TITLE
Stoped to work default Site filter.

### ISSUE THREAD

**Issue by OleksiiBrylin** [riasvdv/statamic-redirect#75]
Statamic 3.3.11
Statamic Redirect 2.3.4
Multilang Site Enabled

there is a new issue after v2.3.0 update.
the issue in 2.3.4 too

In any collection on a page of entries list stoped to work default Site filter.
After the addon update a user sees all entries from all locales.

Expected behavior: the user sees Site: {Locale} filter by default on Entries list page. All entries filtered by the locale

**Comment by axelferdinand** [comment]
I need a fix for this, too.
