### ISSUE TITLE
Error on multisite when site cannot be determined

### ISSUE THREAD

**Issue by FlorianMoser** [riasvdv/statamic-redirect#77]
I have a multisite installation with a URL prefix for each language (/de, /fr, /en). This means, when accessing the root page /, there is no site determined in Statamic.

So when I create a short URL /my-short-url that should redirect to a specific URL /en/my-longer-url I get the error "Call to a member function handle() on null" in vendor/rias/statamic-redirect/src/Http/Middleware/HandleNotFound.php:47 because $site is null.

**Comment by riasvdv** [comment]
Ah, that's a use case I hadn't thought of, I'll look into this soon!
