### ISSUE TITLE
Get 500 server error on CSV upload

### ISSUE THREAD

**Issue by axelferdinand** [riasvdv/statamic-redirect#78]
I'm trying to upload a CSV file in with the recommended formatting, but get 500 server error on upload.

Is there something wrong with my server setup?

<img width="451" alt="image010" src="https://user-images.githubusercontent.com/10460870/173757971-aca6b9f5-2a30-44b0-9e74-7d46d5c63163.png">
![unnamed](https://user-images.githubusercontent.com/10460870/173757972-72b7a01f-fda5-4f8f-8a7b-6a2e4009c427.png)

**Comment by riasvdv** [comment]
Could you take a look in your laravel.log file which error it is?

**Comment by axelferdinand** [comment]
Hi @riasvdv You can close this, I just discovered my new test file went through. Must have been something wrong with the first file. Thanks!
