### ISSUE TITLE
High server load with addon installed

### ISSUE THREAD

**Issue by AG-Steve** [riasvdv/statamic-redirect#8]
With the addon installed on our staging server all is good but on production which is running on the same environment setup the server load is so high it takes our website offline. It's an old domain with many 404 requests coming in. We can turn off 'clean_errors_on_save' in the config but would ideally like to turn off 404 logging altogether, even just the interface for adding manual redirects alone would be good enough.
Currently we can't use the addon, any ideas how we can reduce the high server load or any plans to update the addon with more options to control logging?

**Comment by riasvdv** [comment]
An option to disable the logging is a good idea, I'll try to implement this this week, but with the holidays I can't make a hard promise

**Comment by riasvdv** [comment]
You can now disable logging of errors in 1.4.0
