### ISSUE TITLE
Redirects not working

### ISSUE THREAD

**Issue by cristawebadmin** [riasvdv/statamic-redirect#83]
Hello, we just noticed that a couple of our redirects are not working. These redirects worked before and are enabled, but it doesn't seem to be working any longer. 

When we go in and edit the redirect and save it, it then works. When I looked at the directory, I found out that only the redirects that are inside the `redirects > default` folder works. All other redirects that are outside the `default` folder goes to a 404. Re-saving the redirect in the dashboard would move the .yaml file to the defaults folder and then would make the redirect work again. 

Was this change intended? How can we avoid this issue in the future? For now, we just manually moved all our .yaml redirect inside the `redirects > default` folder to make the redirects work again. Please advise. Thanks!

- Statamic 3.3.18
- Statamic Redirect 2.3.6

<img width="696" alt="image" src="https://user-images.githubusercontent.com/28016899/177610531-d99bdb5e-f346-4fe8-91b8-65366ab2454a.png">

**Comment by riasvdv** [comment]
Hmm, the update script should have ran to move all your redirects to the "default" site (see https://github.com/riasvdv/statamic-redirect/blob/main/src/UpdateScripts/MoveRedirectsToDefaultSite.php)

The change was definitely intended, maybe the script didn't run on your production? Or aren't set up completely? https://statamic.dev/tips/configuring-update-scripts#running-update-scripts-for-the-first-time

**Comment by axooh** [comment]
We have the same issue. Update script didn't run on any environment (local, dev, production).

**Comment by duncanmcclean** [comment]
I've just ran into the same issue, in development.

**Comment by imbwaldo** [comment]
Thanks, @duncanmcclean, for investigating and fixing this issue.
