### ISSUE TITLE
Disabling error logging stops regex-matched redirects from redirecting

### ISSUE THREAD

**Issue by monika** [riasvdv/statamic-redirect#85]
- Statamic 3.2.39
- Redirects 2.3.6

I'm monitoring 404s with another service so I usually have error logging disabled for this addon. When upgrading to version 2.* since I upgraded Statamic to 3.2, I found that when disabling error logging with `REDIRECT_LOG_ERRORS=false` in my .env (or in the config file itself) my regex-matched redirects don't redirect. Exact-matched redirects still redirect as usual, though.

**Comment by duncanmcclean** [comment]
Ah, I'm running into the same thing but with non-regex redirects. I have `REDIRECT_LOG_ERRORS=false` set in my `.env`

**Comment by riasvdv** [comment]
Should be fixed in 2.3.8! And 2.3.9 should at least report exceptions to your exception tracker if something like this happens in the future
