### ISSUE TITLE
PHP8 support

### ISSUE THREAD

**Issue by lBodia** [riasvdv/statamic-redirect#9]
Currently, it is not possible to use this package with PHP8 as `"spatie/data-transfer-object": "^1.13"` uses still `^7.1`.
Also, I didn't find any usage of spatie package inside.
Could you please update the version or just remove it (if it is not needed), so we can still use statamic-redirect with PHP8?
Thank you

**Comment by riasvdv** [comment]
I'll fix this soon!

**Comment by riasvdv** [comment]
Should be fixed in 1.3.2
