### ISSUE TITLE
Ability to re-order Redirects

### ISSUE THREAD

**Issue by JayGeorge** [riasvdv/statamic-redirect#92]
It would be really useful to be able to re-order redirects.

## Example Use Case

I ran into this on a site recently where I first recreated a general redirect rule (`/our-experiences(.*)`) but then realised I needed some specific redirect rules to override this. Since these specific rules were added _afterwards_, the preceding general rule took priority.

![Screenshot 2022-08-05 at 13 04 35](https://user-images.githubusercontent.com/693601/183079185-42a34333-f6a1-417d-9b88-2c6d37c2e46f.jpg)

**Comment by j-jalving** [comment]
This would be very useful

**Comment by riasvdv** [comment]
You can now re-order redirects in 3.2.0
